const ITEM_WIDTH = 1050;

export default {
  EditCollections: {
    display: 'flex',
    justifyContent: 'flext-start',
    alignItems: 'center',
    flexDirection: 'column',
    width: '100%',
    maxHeight: '100vh',
    margin: '64px 0px 0px 0px',
  },
  menuBar: {
    height: '50px',
    width: ITEM_WIDTH,
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'center',
    fontWeight: 'bold',
  },
  headerWrapperActive: {
    height: '50px',
    width: '20%',
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingLeft: '10px',
  },
  headerWrapper: {
    height: '50px',
    width: '15%',
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'center',
    padding: '0px 0px 0px 0px',
    fontSize: '1rem',
  },
  headerLink: {
    color: 'var(--text-primary-light)',
    textDecoration: 'none',
    transition: 'all 300ms ease-in-out',
    '&:hover': {
      color: 'var(--text-accept-light)',
    },
  },
  headerTextActive: {
    animationName: '$edit-decks-slide-in',
    animationDuration: '500ms',
    animationIterationCount: 1,
    animationTimingFunction: 'ease-in-out',
  },
  headerText: {
    animationName: '$edit-decks-slide-in',
    animationDuration: '500ms',
    animationIterationCount: 1,
    animationTimingFunction: 'ease-in-out',
  },
  '@keyframes edit-decks-slide-in': {
    '0%': {
      opacity: 0,
      transform: 'translateY(20%)',
    },
    '50%': {
      opacity: 0.4,
    },
  },
  navWrapperOuter: {
    height: '50px',
    width: '50%',
    display: 'flex',
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  navWrapperInner: {
    height: '50px',
    width: '70%',
    display: 'flex',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    '& .MuiTab-root.MuiTab-textColorPrimary.Mui-selected': {
      color: 'var(--tab-primary)',
    },
    '& .MuiTabs-indicator': {
      backgroundColor: 'var(--tab-primary)',
    },
  },
  filterWrapper: {
    height: '50px',
    width: '20%',
    display: 'flex',
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingRight: '10px',
    marginLeft: 'auto',

  },
  divider: {
    height: '1px',
    width: ITEM_WIDTH,
    borderBottom: '1px solid rgba(0, 0, 0, 0.2)',
    margin: '0px 0px 5px 0px',
    padding: '0px 0px 2px 0px',
  },
  dividerEnd: {
    height: '1px',
    width: '1020px',
    borderBottom: '1px solid rgba(0, 0, 0, 0.2)',
    margin: '0px 0px 5px 0px',
    padding: '4px 0px 2px 0px',
    // boxShadow: '0px 1px 3px 0px rgba(0, 0, 0, 0.1)',
  },
  mainCard: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
    flexDirection: 'column',
    width: '1125px',
    height: '85vh',
    overflow: 'none',
    padding: '15px 0px 0px 0px',
    margin: '0px 0px 0px 0px',
    borderRadius: '2px',
    boxShadow: '0px 1px 5px 1px rgba(0, 0, 0, 0.1)',
    backgroundColor: 'var(--background-collection-main)',
    fontSize: '1rem',
    fontWeight: '400',
  },
  itemsWrapperOuter: {
    height: '100%',
    overflow: 'scroll',
  },
  itemsWrapper: {
    backgroundColor: 'var(--background-collection-container)',
    height: '99%',
    overflow: 'scroll',
    display: 'flex',
    justifyContent: 'center',
    border: '2px solid rgba(0, 0, 0, 0.04)',
    width: '1020px',
  },
  headerCardWrapper: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    width: ITEM_WIDTH,
    height: '60px',
    backgroundColor: '(var(--background-white))',
  },
  headerCard: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    width: '1000px',
    height: '55px',
    padding: '0px 0px 0px 0px',
    margin: '0px 0px 0px 0px',
    borderRadius: '5px',
    color: 'var(--text-primary)',
    backgroundColor: 'var(--background-white)',
    fontSize: '1rem',
    fontWeight: 'bold',
  },
  setNameWrapper: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
    width: '25%',
    height: '50px',
    padding: '0px 0px 0px 15px',
    '& p': {
      whiteSpace: 'no-wrap',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
  },
  categoryWrapper: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
    width: '25%',
    height: '50px',
    padding: '0px 0px 0px 15px',
  },
  masteryWrapper: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '10%',
    height: '50px',
  },
  totalCardsWrapper: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '10%',
    height: '50px',
  },
  iconWrapper: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '10%',
    height: '50px',
  },
  actionsWrapper: {
    height: '50px',
    width: '20%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  addIconWrapper: {
    paddingTop: '4px',
    marginBottom: '5px',
    height: '40px',
    width: '120px',
    display: 'flex',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    // flexDirection: 'column',
    boxShadow: '0px 1px 1px 0px rgba(0, 0, 0, 0.05)',
    fontSize: '1.8rem',
    borderRadius: '4px',
    border: '1px solid rgba(0, 0, 0, 0.2)',
    color: 'var(--text-primary)',
    transition: 'all 0.4s ease 0s',
    '& p': {
      fontSize: '.9rem',
      margin: '0px 0px 0px 0px',
    },
    '& i': {
      margin: '0px 0px 0px 0px',
      fontSize: '1.3rem',
    },
    '&:hover': {
      color: 'var(--text-accept)',
      transition: 'all 0.4s ease 0s',
      cursor: 'pointer',
      boxShadow: '0px 1px 3px 0px rgba(0, 0, 0, 0.3)',

    },
  },
  loadingSpinnerWrapper: {
    height: '610px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  sortIconWrapper: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '30px',
    height: '100%',
    paddingBottom: '2px',
  },
  sortClickWrapper: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    '&:hover': {
      cursor: 'pointer',
    },
  },
  pageButtonWrapper: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '50px',
  },
  viewingButtonWrapper: {
    display: 'flex',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    width: '300px',
    height: '75px',
    // border: '1px solid black',
  },
  viewingButtonWrapperEmpty: {
    display: 'flex',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    width: '300px',
    height: '75px',
    // border: '1px solid black',
  },

};
