export default {
  Login: {
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  LoginCardTop: {
    // border: '1px solid black',
    display: 'flex',
    justifyContent: 'center',
    alightItems: 'center',
    height: '22.5%',
    width: '100%',
  },
  LoginCardTopTextWrapper: {
    display: 'flex',
    justifyContent: 'center',
    alightItems: 'center',
    flexDirection: 'column',
    paddingTop: '20px',
  },
  signInText: {
    paddingTop: '25px',
  },
  inputWrapper: {
    display: 'flex',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    flexDirection: 'column',
    // border: '1px solid black',
    width: '100%',
    height: '28.25%',
    paddingBottom: '0px',
  },
  buttonWrapper: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
    // border: '1px solid black',
    height: '18.75%',
    width: '100%',
  },
  loginButton: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: 'white',
    textTransform: 'uppercase',
    textDecoration: 'none',
    fontFamily: "'Roboto', 'Helvetica', 'Arial', sans-serif",
    fontSize: '16px',
    fontWeight: '400',
    background: 'rgba(0, 0, 0, 0.7)',
    width: '125px',
    height: '50px',
    border: '1.5px solid rgba(0, 0, 0, 0.7)',
    transition: 'all 0.4s ease 0s',
    borderRadius: '5px',
    '& svg': {
      fontSize: '30px',
    },
    '&:hover': {
      background: 'rgba(7, 177, 77, 0.7)',
      borderColor: 'rgba(7, 177, 77, 0.7)',
      transition: 'all 0.4s ease 0s',
      cursor: 'pointer',
    },
  },
  noAccountWrapper: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'flex-start',
    // border: '1px solid black',
    height: '7.5%',
    width: '100%',
  },
  noAccountText: {
    display: 'flex',
    paddingLeft: '25px',
    '&:hover': {
      cursor: 'pointer',
    },
    '& .navArrow': {
      color: 'rgba(0, 0, 0, 0)',
      paddingBottom: '4px',
      transition: 'all .25s',
      transitionTimingFunction: 'ease-in-out',
    },
    '&:hover .navArrow': {
      color: 'rgba(0, 0, 0, .8)',
      transform: 'translateX(35%)',
    },
  },
  dividerBlock: {
    display: 'flex',
    justifyContent: 'center',
    alightItems: 'center',
    height: '8.33%',
    width: '100%',
    // border: '1px solid black',
  },
  dividerLine: {
    display: 'flex',
    alignSelf: 'center',
    height: '1px',
    width: '38%',
    borderBottom: '1px solid rgba(0, 0, 0, 0.4)',
  },
  dividerText: {
    display: 'flex',
    alignSelf: 'center',
    padding: '0px 10px 0px 10px',
    fontSize: '14px',
  },
  iconsWrapper: {
    // border: '1px solid black',
    display: 'flex',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    height: '14.66%',
    width: '75%',
    marginBottom: '15px',
    '& svg': {
      fontSize: '35px',
      color: 'rgba(0, 0, 0, 0.7)',
      '&.facebook': {
        fontSize: '42px',
        transition: 'all 0.4s ease 0s',
        '&:hover': {
          color: 'rgba(7, 177, 77, 0.7)',
          transition: 'all 0.4s ease 0s',
          cursor: 'pointer',
        },
      },
      '&.google': {
        fontSize: '39px',
        transition: 'all 0.4s ease 0s',
        '&:hover': {
          color: 'rgba(7, 177, 77, 0.7)',
          transition: 'all 0.4s ease 0s',
          cursor: 'pointer',
        },
      },
      '&.github': {
        transition: 'all 0.4s ease 0s',
        '&:hover': {
          color: 'rgba(7, 177, 77, 0.7)',
          transition: 'all 0.4s ease 0s',
          cursor: 'pointer',
        },

      },
    },
  },
};
