export default [
  {
    id: 'microscope',
    name: 'Microscope',
    class: 'fas fa-microscope',
    filter: 'Science',
  },
  {
    id: 'vial',
    name: 'Vial',
    class: 'fas fa-vial',
    filter: 'Science',
  },
  {
    id: 'atom',
    name: 'Atom',
    class: 'fas fa-atom',
    filter: 'Science',
  },
  {
    id: 'code',
    name: 'Code',
    class: 'fas fa-code',
    filter: 'Technology',
  },
  {
    id: 'codeBranch',
    name: 'Code Branch',
    class: 'fas fa-code-branch',
    filter: 'Technology',
  },
  {
    id: 'laptopCode',
    name: 'Laptop Code',
    class: 'fas fa-laptop-code',
    filter: 'Technology',
  },
  {
    id: 'film',
    name: 'Film',
    class: 'fas fa-film',
    filter: 'Entertainment',
  },
  {
    id: 'headphones',
    name: 'Headphones',
    class: 'fas fa-headphones',
    filter: 'Music',
  },
  {
    id: 'microphone',
    name: 'Microphone',
    class: 'fas fa-microphone',
    filter: 'Music',
  },
  {
    id: 'video',
    name: 'Video',
    class: 'fas fa-video',
    filter: 'Entertainment',
  },
  {
    id: 'monument',
    name: 'Monument',
    class: 'fas fa-monument',
    filter: 'Historic',
  },
  {
    id: 'landmark',
    name: 'Landmark',
    class: 'fas fa-landmark',
    filter: 'Historic',
  },
  {
    id: 'water',
    name: 'Water',
    class: 'fas fa-water',
    filter: 'Nature',
  },
  {
    id: 'tree',
    name: 'Tree',
    class: 'fas fa-tree',
    filter: 'Nature',
  },
  {
    id: 'running',
    name: 'Running',
    class: 'fas fa-running',
    filter: 'Sports',
  },
  {
    id: 'baseballBall',
    name: 'Baseball Ball',
    class: 'fas fa-baseball-ball',
    filter: 'Sports',
  },
  {
    id: 'tableTennis',
    name: 'Table Tennis',
    class: 'fas fa-table-tennis',
    filter: 'Sports',
  },
  {
    id: 'tv',
    name: 'TV',
    class: 'fas fa-tv',
    filter: 'Entertainment',
  },
  {
    id: 'globeAmericas',
    name: 'Globe Americas',
    class: 'fas fa-globe-americas',
    filter: 'Historic',
  },
  {
    id: 'music',
    name: 'Music',
    class: 'fas fa-music',
    filter: 'Music',
  },
  {
    id: 'recordVinyl',
    name: 'Record Vinyl',
    class: 'fas fa-record-vinyl',
    filter: 'Music',
  },
  {
    id: 'guitar',
    name: 'Guitar',
    class: 'fas fa-guitar',
    filter: 'Music',
  },
  {
    id: 'drum',
    name: 'Drum',
    class: 'fas fa-drum',
    filter: 'Music',
  },
  {
    id: 'podcast',
    name: 'Podcast',
    class: 'fas fa-podcast',
    filter: 'Entertainment',
  },
  {
    id: 'school',
    name: 'School',
    class: 'fas fa-school',
    filter: 'Education',
  },
  {
    id: 'graduationCap',
    name: 'Graduation Cap',
    class: 'fas fa-graduation-cap',
    filter: 'Education',
  },
  {
    id: 'bookOpen',
    name: 'Book Open',
    class: 'fas fa-book-open',
    filter: 'Education',
  },
  {
    id: 'theaterMasks',
    name: 'Theater Masks',
    class: 'fas fa-theater-masks',
    filter: 'Entertainment',
  },
  {
    id: 'cat',
    name: 'Cat',
    class: 'fas fa-cat',
    filter: 'Animals',
  },
  {
    id: 'dog',
    name: 'Dog',
    class: 'fas fa-dog',
    filter: 'Animals',
  },
  {
    id: 'frog',
    name: 'Frog',
    class: 'fas fa-frog',
    filter: 'Animals',
  },
  {
    id: 'horse',
    name: 'Horse',
    class: 'fas fa-horse',
    filter: 'Animals',
  },
  {
    id: 'fish',
    name: 'Fish',
    class: 'fas fa-fish',
    filter: 'Animals',
  },
  {
    id: 'jediOrder',
    name: 'Jedi Order',
    class: 'fab fa-jedi-order',
    filter: 'Space',
  },
  {
    id: 'meteor',
    name: 'Meteor',
    class: 'fas fa-meteor',
    filter: 'Space',
  },
  {
    id: 'moon',
    name: 'Moon',
    class: 'fas fa-moon',
    filter: 'Space',
  },
  {
    id: 'rocket',
    name: 'Rocket',
    class: 'fas fa-rocket',
    filter: 'Space',
  },
  {
    id: 'satellite',
    name: 'Satellite',
    class: 'fas fa-satellite',
    filter: 'Space',
  },
  {
    id: 'hamburger',
    name: 'Hamburger',
    class: 'fas fa-hamburger',
    filter: 'Food',
  },
  {
    id: 'pepperHot',
    name: 'Pepper Hot',
    class: 'fas fa-pepper-hot',
    filter: 'Food',
  },
  {
    id: 'pizzaSlice',
    name: 'Pizza Slice',
    class: 'fas fa-pizza-slice',
    filter: 'Food',
  },
  // {
  //   id: '',
  //   name: '',
  //   class: 'fas fa-',
  //   filter: '',
  // },
  // {
  //   id: '',
  //   name: '',
  //   class: 'fas fa-',
  //   filter: '',
  // },

];
